# Configuración del Servidor
server.port=8080

# Conexión a Base de Datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/emplanorte
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
# Usamos 'none' para respetar al 100% el script SQL estructurado en 01_schema.sql
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Configuración de Jackson para serialización JSON limpia
spring.jackson.serialization.write-dates-as-timestamps=false
